version: "3"

services:
  temp_sensor:
    image: celjon/data-simulator
    environment:
      - SIM_HOST=192.168.28.1
      - SIM_NAME=TEMP1
      - SIM_PERIOD=5
      - SIM_TYPE=temperature
  pressure_sensor:
    image: celjon/data-simulator
    environment:
      - SIM_HOST=192.168.28.1
      - SIM_NAME=PRES1
      - SIM_PERIOD=10
      - SIM_TYPE=pressure
  current_sensor:
    image: celjon/data-simulator
    environment:
      - SIM_HOST=192.168.28.1
      - SIM_NAME=CURRENT!
      - SIM_PERIOD=1
      - SIM_TYPE=current
